version: '3.5'
services:
  db:
    restart: always
    image: postgres:9.6-alpine
    networks:
      - back-mstdn
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - back-mstdn
    volumes:
      - ./redis:/data
  web:
    #build: .
    image: frfs/mastodon
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - back-mstdn
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
#      - es
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    #build: .
    image: frfs/mastodon
    restart: always
    env_file: .env.production
    command: yarn start
    networks:
      - back-mstdn
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    #build: .
    image: frfs/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -c 20 -q default -q push -q mailers -q pull
    depends_on:
      - db
      - redis
    networks:
      - back-mstdn
    volumes:
      - ./public/system:/mastodon/public/system

networks:
  back-mstdn:
    name: back-mstdn
      external: true
