version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
          docker build -t frfs/mastodon . --build-arg DEFAULT_HASHTAG=frfr
          docker push frfs/mastodon 
