version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
          touch .env.production
          docker-compose build web
          docker-compose push web